name: Build App 1

on:
  push:
    branches: [ "main" ]
    paths:
      - app1/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./app1 --file ./app1/Dockerfile --tag benhesketh21/app1:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    - name: Docker Login
      run: docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password "${{ secrets.DOCKER_HUB_PASSWORD }}"
    - name: Docker Push
      run: docker push benhesketh21/app1:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}