name: Build App 1

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./app1 --file ./app1/Dockerfile --tag benhesketh21/app1:main-$(date +%s)
