name: Build App 1

on:
  push:
    branches:
      - main
      - release/*
    paths:
      - app1/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./app1 --file ./app1/Dockerfile --tag benhesketh21/app1:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    - name: Docker Login
      run: docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password "${{ secrets.DOCKER_HUB_PASSWORD }}"
    - name: Docker Push
      run: docker push benhesketh21/app1:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    - run: |
        gh release create "app1-${GITHUB_REF_NAME}-${GITHUB_RUN_ID}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        gh workflow run test-main -R BenHesketh21/gitops-release-branches-argo
      env:
        GH_TOKEN: ${{ secrets.CROSS_REPO_GH_TOKEN }}