name: Build App 2

on:
  push:
    branches: [ "main" ]
    paths:
      - app2
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./app2 --file ./app2/Dockerfile --tag benhesketh21/app2:main-$(date +%s)
